module.exports = {
	ROUTE_LOGIN: '/api/login',
	ROUTE_CASH_CATEGORY_ITEM: '/api/cash-category-item',
	ROUTE_CURRENCIES: '/api/currencies',
	ROUTE_CONVERSION_RATES: '/api/conversion-rates',
	ROUTE_CASH_STATISTICS: '/api/cash-statistics',
	ROUTE_GET_CASH_STRUCTURE: '/api/cash-categories',
	ROUTE_CREATE_STATISTICS_RECORD: '/api/create-statistics-record',
	ROUTE_BANK_ORGANIZATION: '/api/bank-organization',
	ROUTE_BANK_ACCOUNT: '/api/bank-organization/account',
	ROUTE_BANK_AVATAR: '/api/bank-organization/avatar',
	ROUTE_BROKER: '/api/broker',
	ROUTE_BROKER_ASSETS: '/api/broker/assets',
	ROUTE_BROKER_AVATAR: '/api/broker/avatar',
};