module.exports = {
    ROUTE_LOGIN: '/login',
    ROUTE_CASH_CATEGORY_ITEM: '/cash-category-item',
    ROUTE_CURRENCIES: '/currencies',
    ROUTE_CONVERSION_RATES: '/conversion-rates',
    ROUTE_CASH_STATISTICS: '/cash-statistics',
    ROUTE_GET_CASH_STRUCTURE: '/cash-categories',
    ROUTE_CREATE_STATISTICS_RECORD: '/create-statistics-record',
    ROUTE_BANK_ORGANIZATION: '/bank-organization',
    ROUTE_BANK_ACCOUNT: '/bank-organization/account',
    ROUTE_BANK_AVATAR: '/bank-organization/avatar',
    ROUTE_BROKER: '/broker',
    ROUTE_BROKER_ASSETS: '/broker/assets',
	ROUTE_BROKER_AVATAR: '/broker/avatar',
}